CREATE TABLE IF NOT EXISTS rtc_room_state (
  room_id VARCHAR(128) NOT NULL COMMENT 'ZEGO 房间号',
  status VARCHAR(32) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING,ACTIVE,ENDED,ABNORMAL',
  doctor_user_id VARCHAR(64) DEFAULT NULL,
  doctor_stream_id VARCHAR(256) DEFAULT NULL,
  doctor_lease_id VARCHAR(32) DEFAULT NULL,
  doctor_last_seen_at BIGINT NOT NULL DEFAULT 0,
  peer_user_id VARCHAR(64) DEFAULT NULL,
  peer_stream_id VARCHAR(256) DEFAULT NULL,
  peer_lease_id VARCHAR(32) DEFAULT NULL,
  peer_last_seen_at BIGINT NOT NULL DEFAULT 0,
  started_at BIGINT NOT NULL DEFAULT 0,
  ended_at BIGINT NOT NULL DEFAULT 0,
  abnormal_at BIGINT NOT NULL DEFAULT 0,
  last_heartbeat_at BIGINT NOT NULL DEFAULT 0,
  state_updated_at BIGINT NOT NULL DEFAULT 0,
  last_event VARCHAR(64) DEFAULT NULL,
  last_error VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (room_id),
  KEY idx_rtc_room_state_status_updated (status, state_updated_at),
  KEY idx_rtc_room_state_doctor (doctor_user_id),
  KEY idx_rtc_room_state_peer (peer_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ZEGO 通话房间状态';

CREATE TABLE IF NOT EXISTS rtc_audit_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  action VARCHAR(64) NOT NULL COMMENT 'SESSION,HEARTBEAT,LEAVE,END,REJECT,EXPIRE 等',
  result VARCHAR(32) NOT NULL COMMENT 'SUCCESS,FAIL',
  room_id VARCHAR(128) DEFAULT NULL,
  user_id VARCHAR(64) DEFAULT NULL,
  role VARCHAR(32) DEFAULT NULL,
  slot_type VARCHAR(32) DEFAULT NULL,
  stream_id VARCHAR(256) DEFAULT NULL,
  order_id VARCHAR(64) DEFAULT NULL,
  client_type VARCHAR(32) DEFAULT NULL,
  client_ip VARCHAR(64) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  ticket_hash VARCHAR(64) DEFAULT NULL,
  message VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_rtc_audit_room_time (room_id, created_at),
  KEY idx_rtc_audit_user_time (user_id, created_at),
  KEY idx_rtc_audit_action_time (action, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ZEGO 通话审计日志';

CREATE TABLE IF NOT EXISTS rtc_recording_task (
  task_id VARCHAR(64) NOT NULL COMMENT '本地录制任务 ID',
  room_id VARCHAR(128) NOT NULL COMMENT 'ZEGO 房间号',
  order_id VARCHAR(128) DEFAULT NULL COMMENT '业务订单号，来自请求参数',
  doctor_user_id VARCHAR(64) DEFAULT NULL COMMENT '医生端 userID',
  peer_user_id VARCHAR(64) DEFAULT NULL COMMENT '患者或药店端 userID',
  doctor_name VARCHAR(64) DEFAULT NULL COMMENT '医生真实姓名，来自 chbzg1 订单',
  peer_name VARCHAR(64) DEFAULT NULL COMMENT '患者或药店真实姓名，来自 chbzg1 订单',
  status VARCHAR(32) NOT NULL DEFAULT 'STARTING' COMMENT 'STARTING,RUNNING,STOPPED,UPLOADED,UPLOAD_FAILED,FAILED,ABNORMAL',
  output_file VARCHAR(512) DEFAULT NULL COMMENT '本地临时 MP4 路径，仅用于调试和失败重试',
  log_file VARCHAR(512) DEFAULT NULL COMMENT '录制 SDK 日志文件路径',
  local_file_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '上传成功后本地 MP4 是否已删除',
  local_file_deleted_at BIGINT NOT NULL DEFAULT 0 COMMENT '本地 MP4 删除时间',
  oss_bucket VARCHAR(128) DEFAULT NULL COMMENT 'OSS bucket',
  oss_object_key VARCHAR(512) DEFAULT NULL COMMENT 'OSS object key，后台长期播放依据',
  oss_url VARCHAR(1024) DEFAULT NULL COMMENT 'OSS 原始 URL 或 object key，不作为私有 bucket 播放凭证',
  file_size BIGINT NOT NULL DEFAULT 0 COMMENT '录制文件大小，字节',
  duration_seconds DOUBLE DEFAULT NULL COMMENT '录制时长，秒，ffprobe 可用时写入',
  started_at BIGINT NOT NULL DEFAULT 0,
  ended_at BIGINT NOT NULL DEFAULT 0,
  uploaded_at BIGINT NOT NULL DEFAULT 0,
  upload_attempts INT NOT NULL DEFAULT 0,
  next_upload_at BIGINT NOT NULL DEFAULT 0,
  message VARCHAR(1024) DEFAULT NULL,
  last_error VARCHAR(1024) DEFAULT NULL,
  created_at BIGINT NOT NULL DEFAULT 0,
  state_updated_at BIGINT NOT NULL DEFAULT 0,
  db_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  db_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (task_id),
  KEY idx_rtc_recording_room_time (room_id, started_at),
  KEY idx_rtc_recording_order_time (order_id, started_at),
  KEY idx_rtc_recording_status_time (status, started_at),
  KEY idx_rtc_recording_upload_retry (status, next_upload_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ZEGO 本地录制任务与 OSS 资产';
